
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `links` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model links
 * 
 */
export type linksModel = runtime.Types.Result.DefaultSelection<Prisma.$linksPayload>

export type AggregateLinks = {
  _count: LinksCountAggregateOutputType | null
  _min: LinksMinAggregateOutputType | null
  _max: LinksMaxAggregateOutputType | null
}

export type LinksMinAggregateOutputType = {
  id: string | null
  type: $Enums.LinkType | null
  label: string | null
  url: string | null
  profileId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type LinksMaxAggregateOutputType = {
  id: string | null
  type: $Enums.LinkType | null
  label: string | null
  url: string | null
  profileId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type LinksCountAggregateOutputType = {
  id: number
  type: number
  label: number
  url: number
  profileId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type LinksMinAggregateInputType = {
  id?: true
  type?: true
  label?: true
  url?: true
  profileId?: true
  createdAt?: true
  updatedAt?: true
}

export type LinksMaxAggregateInputType = {
  id?: true
  type?: true
  label?: true
  url?: true
  profileId?: true
  createdAt?: true
  updatedAt?: true
}

export type LinksCountAggregateInputType = {
  id?: true
  type?: true
  label?: true
  url?: true
  profileId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type LinksAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which links to aggregate.
   */
  where?: Prisma.linksWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of links to fetch.
   */
  orderBy?: Prisma.linksOrderByWithRelationInput | Prisma.linksOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.linksWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` links from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` links.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned links
  **/
  _count?: true | LinksCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LinksMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LinksMaxAggregateInputType
}

export type GetLinksAggregateType<T extends LinksAggregateArgs> = {
      [P in keyof T & keyof AggregateLinks]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLinks[P]>
    : Prisma.GetScalarType<T[P], AggregateLinks[P]>
}




export type linksGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.linksWhereInput
  orderBy?: Prisma.linksOrderByWithAggregationInput | Prisma.linksOrderByWithAggregationInput[]
  by: Prisma.LinksScalarFieldEnum[] | Prisma.LinksScalarFieldEnum
  having?: Prisma.linksScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LinksCountAggregateInputType | true
  _min?: LinksMinAggregateInputType
  _max?: LinksMaxAggregateInputType
}

export type LinksGroupByOutputType = {
  id: string
  type: $Enums.LinkType
  label: string | null
  url: string | null
  profileId: string
  createdAt: Date
  updatedAt: Date
  _count: LinksCountAggregateOutputType | null
  _min: LinksMinAggregateOutputType | null
  _max: LinksMaxAggregateOutputType | null
}

type GetLinksGroupByPayload<T extends linksGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LinksGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LinksGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LinksGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LinksGroupByOutputType[P]>
      }
    >
  >



export type linksWhereInput = {
  AND?: Prisma.linksWhereInput | Prisma.linksWhereInput[]
  OR?: Prisma.linksWhereInput[]
  NOT?: Prisma.linksWhereInput | Prisma.linksWhereInput[]
  id?: Prisma.StringFilter<"links"> | string
  type?: Prisma.EnumLinkTypeFilter<"links"> | $Enums.LinkType
  label?: Prisma.StringNullableFilter<"links"> | string | null
  url?: Prisma.StringNullableFilter<"links"> | string | null
  profileId?: Prisma.StringFilter<"links"> | string
  createdAt?: Prisma.DateTimeFilter<"links"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"links"> | Date | string
  profile?: Prisma.XOR<Prisma.ProfileScalarRelationFilter, Prisma.ProfileWhereInput>
}

export type linksOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  label?: Prisma.SortOrderInput | Prisma.SortOrder
  url?: Prisma.SortOrderInput | Prisma.SortOrder
  profileId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  profile?: Prisma.ProfileOrderByWithRelationInput
}

export type linksWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.linksWhereInput | Prisma.linksWhereInput[]
  OR?: Prisma.linksWhereInput[]
  NOT?: Prisma.linksWhereInput | Prisma.linksWhereInput[]
  type?: Prisma.EnumLinkTypeFilter<"links"> | $Enums.LinkType
  label?: Prisma.StringNullableFilter<"links"> | string | null
  url?: Prisma.StringNullableFilter<"links"> | string | null
  profileId?: Prisma.StringFilter<"links"> | string
  createdAt?: Prisma.DateTimeFilter<"links"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"links"> | Date | string
  profile?: Prisma.XOR<Prisma.ProfileScalarRelationFilter, Prisma.ProfileWhereInput>
}, "id">

export type linksOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  label?: Prisma.SortOrderInput | Prisma.SortOrder
  url?: Prisma.SortOrderInput | Prisma.SortOrder
  profileId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.linksCountOrderByAggregateInput
  _max?: Prisma.linksMaxOrderByAggregateInput
  _min?: Prisma.linksMinOrderByAggregateInput
}

export type linksScalarWhereWithAggregatesInput = {
  AND?: Prisma.linksScalarWhereWithAggregatesInput | Prisma.linksScalarWhereWithAggregatesInput[]
  OR?: Prisma.linksScalarWhereWithAggregatesInput[]
  NOT?: Prisma.linksScalarWhereWithAggregatesInput | Prisma.linksScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"links"> | string
  type?: Prisma.EnumLinkTypeWithAggregatesFilter<"links"> | $Enums.LinkType
  label?: Prisma.StringNullableWithAggregatesFilter<"links"> | string | null
  url?: Prisma.StringNullableWithAggregatesFilter<"links"> | string | null
  profileId?: Prisma.StringWithAggregatesFilter<"links"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"links"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"links"> | Date | string
}

export type linksCreateInput = {
  id?: string
  type: $Enums.LinkType
  label?: string | null
  url?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  profile: Prisma.ProfileCreateNestedOneWithoutLinksInput
}

export type linksUncheckedCreateInput = {
  id?: string
  type: $Enums.LinkType
  label?: string | null
  url?: string | null
  profileId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type linksUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumLinkTypeFieldUpdateOperationsInput | $Enums.LinkType
  label?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  profile?: Prisma.ProfileUpdateOneRequiredWithoutLinksNestedInput
}

export type linksUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumLinkTypeFieldUpdateOperationsInput | $Enums.LinkType
  label?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profileId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type linksCreateManyInput = {
  id?: string
  type: $Enums.LinkType
  label?: string | null
  url?: string | null
  profileId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type linksUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumLinkTypeFieldUpdateOperationsInput | $Enums.LinkType
  label?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type linksUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumLinkTypeFieldUpdateOperationsInput | $Enums.LinkType
  label?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profileId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LinksListRelationFilter = {
  every?: Prisma.linksWhereInput
  some?: Prisma.linksWhereInput
  none?: Prisma.linksWhereInput
}

export type linksOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type linksCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  label?: Prisma.SortOrder
  url?: Prisma.SortOrder
  profileId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type linksMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  label?: Prisma.SortOrder
  url?: Prisma.SortOrder
  profileId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type linksMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  label?: Prisma.SortOrder
  url?: Prisma.SortOrder
  profileId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type linksCreateNestedManyWithoutProfileInput = {
  create?: Prisma.XOR<Prisma.linksCreateWithoutProfileInput, Prisma.linksUncheckedCreateWithoutProfileInput> | Prisma.linksCreateWithoutProfileInput[] | Prisma.linksUncheckedCreateWithoutProfileInput[]
  connectOrCreate?: Prisma.linksCreateOrConnectWithoutProfileInput | Prisma.linksCreateOrConnectWithoutProfileInput[]
  createMany?: Prisma.linksCreateManyProfileInputEnvelope
  connect?: Prisma.linksWhereUniqueInput | Prisma.linksWhereUniqueInput[]
}

export type linksUncheckedCreateNestedManyWithoutProfileInput = {
  create?: Prisma.XOR<Prisma.linksCreateWithoutProfileInput, Prisma.linksUncheckedCreateWithoutProfileInput> | Prisma.linksCreateWithoutProfileInput[] | Prisma.linksUncheckedCreateWithoutProfileInput[]
  connectOrCreate?: Prisma.linksCreateOrConnectWithoutProfileInput | Prisma.linksCreateOrConnectWithoutProfileInput[]
  createMany?: Prisma.linksCreateManyProfileInputEnvelope
  connect?: Prisma.linksWhereUniqueInput | Prisma.linksWhereUniqueInput[]
}

export type linksUpdateManyWithoutProfileNestedInput = {
  create?: Prisma.XOR<Prisma.linksCreateWithoutProfileInput, Prisma.linksUncheckedCreateWithoutProfileInput> | Prisma.linksCreateWithoutProfileInput[] | Prisma.linksUncheckedCreateWithoutProfileInput[]
  connectOrCreate?: Prisma.linksCreateOrConnectWithoutProfileInput | Prisma.linksCreateOrConnectWithoutProfileInput[]
  upsert?: Prisma.linksUpsertWithWhereUniqueWithoutProfileInput | Prisma.linksUpsertWithWhereUniqueWithoutProfileInput[]
  createMany?: Prisma.linksCreateManyProfileInputEnvelope
  set?: Prisma.linksWhereUniqueInput | Prisma.linksWhereUniqueInput[]
  disconnect?: Prisma.linksWhereUniqueInput | Prisma.linksWhereUniqueInput[]
  delete?: Prisma.linksWhereUniqueInput | Prisma.linksWhereUniqueInput[]
  connect?: Prisma.linksWhereUniqueInput | Prisma.linksWhereUniqueInput[]
  update?: Prisma.linksUpdateWithWhereUniqueWithoutProfileInput | Prisma.linksUpdateWithWhereUniqueWithoutProfileInput[]
  updateMany?: Prisma.linksUpdateManyWithWhereWithoutProfileInput | Prisma.linksUpdateManyWithWhereWithoutProfileInput[]
  deleteMany?: Prisma.linksScalarWhereInput | Prisma.linksScalarWhereInput[]
}

export type linksUncheckedUpdateManyWithoutProfileNestedInput = {
  create?: Prisma.XOR<Prisma.linksCreateWithoutProfileInput, Prisma.linksUncheckedCreateWithoutProfileInput> | Prisma.linksCreateWithoutProfileInput[] | Prisma.linksUncheckedCreateWithoutProfileInput[]
  connectOrCreate?: Prisma.linksCreateOrConnectWithoutProfileInput | Prisma.linksCreateOrConnectWithoutProfileInput[]
  upsert?: Prisma.linksUpsertWithWhereUniqueWithoutProfileInput | Prisma.linksUpsertWithWhereUniqueWithoutProfileInput[]
  createMany?: Prisma.linksCreateManyProfileInputEnvelope
  set?: Prisma.linksWhereUniqueInput | Prisma.linksWhereUniqueInput[]
  disconnect?: Prisma.linksWhereUniqueInput | Prisma.linksWhereUniqueInput[]
  delete?: Prisma.linksWhereUniqueInput | Prisma.linksWhereUniqueInput[]
  connect?: Prisma.linksWhereUniqueInput | Prisma.linksWhereUniqueInput[]
  update?: Prisma.linksUpdateWithWhereUniqueWithoutProfileInput | Prisma.linksUpdateWithWhereUniqueWithoutProfileInput[]
  updateMany?: Prisma.linksUpdateManyWithWhereWithoutProfileInput | Prisma.linksUpdateManyWithWhereWithoutProfileInput[]
  deleteMany?: Prisma.linksScalarWhereInput | Prisma.linksScalarWhereInput[]
}

export type EnumLinkTypeFieldUpdateOperationsInput = {
  set?: $Enums.LinkType
}

export type linksCreateWithoutProfileInput = {
  id?: string
  type: $Enums.LinkType
  label?: string | null
  url?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type linksUncheckedCreateWithoutProfileInput = {
  id?: string
  type: $Enums.LinkType
  label?: string | null
  url?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type linksCreateOrConnectWithoutProfileInput = {
  where: Prisma.linksWhereUniqueInput
  create: Prisma.XOR<Prisma.linksCreateWithoutProfileInput, Prisma.linksUncheckedCreateWithoutProfileInput>
}

export type linksCreateManyProfileInputEnvelope = {
  data: Prisma.linksCreateManyProfileInput | Prisma.linksCreateManyProfileInput[]
  skipDuplicates?: boolean
}

export type linksUpsertWithWhereUniqueWithoutProfileInput = {
  where: Prisma.linksWhereUniqueInput
  update: Prisma.XOR<Prisma.linksUpdateWithoutProfileInput, Prisma.linksUncheckedUpdateWithoutProfileInput>
  create: Prisma.XOR<Prisma.linksCreateWithoutProfileInput, Prisma.linksUncheckedCreateWithoutProfileInput>
}

export type linksUpdateWithWhereUniqueWithoutProfileInput = {
  where: Prisma.linksWhereUniqueInput
  data: Prisma.XOR<Prisma.linksUpdateWithoutProfileInput, Prisma.linksUncheckedUpdateWithoutProfileInput>
}

export type linksUpdateManyWithWhereWithoutProfileInput = {
  where: Prisma.linksScalarWhereInput
  data: Prisma.XOR<Prisma.linksUpdateManyMutationInput, Prisma.linksUncheckedUpdateManyWithoutProfileInput>
}

export type linksScalarWhereInput = {
  AND?: Prisma.linksScalarWhereInput | Prisma.linksScalarWhereInput[]
  OR?: Prisma.linksScalarWhereInput[]
  NOT?: Prisma.linksScalarWhereInput | Prisma.linksScalarWhereInput[]
  id?: Prisma.StringFilter<"links"> | string
  type?: Prisma.EnumLinkTypeFilter<"links"> | $Enums.LinkType
  label?: Prisma.StringNullableFilter<"links"> | string | null
  url?: Prisma.StringNullableFilter<"links"> | string | null
  profileId?: Prisma.StringFilter<"links"> | string
  createdAt?: Prisma.DateTimeFilter<"links"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"links"> | Date | string
}

export type linksCreateManyProfileInput = {
  id?: string
  type: $Enums.LinkType
  label?: string | null
  url?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type linksUpdateWithoutProfileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumLinkTypeFieldUpdateOperationsInput | $Enums.LinkType
  label?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type linksUncheckedUpdateWithoutProfileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumLinkTypeFieldUpdateOperationsInput | $Enums.LinkType
  label?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type linksUncheckedUpdateManyWithoutProfileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumLinkTypeFieldUpdateOperationsInput | $Enums.LinkType
  label?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type linksSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  label?: boolean
  url?: boolean
  profileId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["links"]>

export type linksSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  label?: boolean
  url?: boolean
  profileId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["links"]>

export type linksSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  label?: boolean
  url?: boolean
  profileId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["links"]>

export type linksSelectScalar = {
  id?: boolean
  type?: boolean
  label?: boolean
  url?: boolean
  profileId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type linksOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "type" | "label" | "url" | "profileId" | "createdAt" | "updatedAt", ExtArgs["result"]["links"]>
export type linksInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
}
export type linksIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
}
export type linksIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
}

export type $linksPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "links"
  objects: {
    profile: Prisma.$ProfilePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    type: $Enums.LinkType
    label: string | null
    url: string | null
    profileId: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["links"]>
  composites: {}
}

export type linksGetPayload<S extends boolean | null | undefined | linksDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$linksPayload, S>

export type linksCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<linksFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LinksCountAggregateInputType | true
  }

export interface linksDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['links'], meta: { name: 'links' } }
  /**
   * Find zero or one Links that matches the filter.
   * @param {linksFindUniqueArgs} args - Arguments to find a Links
   * @example
   * // Get one Links
   * const links = await prisma.links.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends linksFindUniqueArgs>(args: Prisma.SelectSubset<T, linksFindUniqueArgs<ExtArgs>>): Prisma.Prisma__linksClient<runtime.Types.Result.GetResult<Prisma.$linksPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Links that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {linksFindUniqueOrThrowArgs} args - Arguments to find a Links
   * @example
   * // Get one Links
   * const links = await prisma.links.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends linksFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, linksFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__linksClient<runtime.Types.Result.GetResult<Prisma.$linksPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Links that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {linksFindFirstArgs} args - Arguments to find a Links
   * @example
   * // Get one Links
   * const links = await prisma.links.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends linksFindFirstArgs>(args?: Prisma.SelectSubset<T, linksFindFirstArgs<ExtArgs>>): Prisma.Prisma__linksClient<runtime.Types.Result.GetResult<Prisma.$linksPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Links that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {linksFindFirstOrThrowArgs} args - Arguments to find a Links
   * @example
   * // Get one Links
   * const links = await prisma.links.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends linksFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, linksFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__linksClient<runtime.Types.Result.GetResult<Prisma.$linksPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Links that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {linksFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Links
   * const links = await prisma.links.findMany()
   * 
   * // Get first 10 Links
   * const links = await prisma.links.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const linksWithIdOnly = await prisma.links.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends linksFindManyArgs>(args?: Prisma.SelectSubset<T, linksFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$linksPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Links.
   * @param {linksCreateArgs} args - Arguments to create a Links.
   * @example
   * // Create one Links
   * const Links = await prisma.links.create({
   *   data: {
   *     // ... data to create a Links
   *   }
   * })
   * 
   */
  create<T extends linksCreateArgs>(args: Prisma.SelectSubset<T, linksCreateArgs<ExtArgs>>): Prisma.Prisma__linksClient<runtime.Types.Result.GetResult<Prisma.$linksPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Links.
   * @param {linksCreateManyArgs} args - Arguments to create many Links.
   * @example
   * // Create many Links
   * const links = await prisma.links.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends linksCreateManyArgs>(args?: Prisma.SelectSubset<T, linksCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Links and returns the data saved in the database.
   * @param {linksCreateManyAndReturnArgs} args - Arguments to create many Links.
   * @example
   * // Create many Links
   * const links = await prisma.links.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Links and only return the `id`
   * const linksWithIdOnly = await prisma.links.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends linksCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, linksCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$linksPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Links.
   * @param {linksDeleteArgs} args - Arguments to delete one Links.
   * @example
   * // Delete one Links
   * const Links = await prisma.links.delete({
   *   where: {
   *     // ... filter to delete one Links
   *   }
   * })
   * 
   */
  delete<T extends linksDeleteArgs>(args: Prisma.SelectSubset<T, linksDeleteArgs<ExtArgs>>): Prisma.Prisma__linksClient<runtime.Types.Result.GetResult<Prisma.$linksPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Links.
   * @param {linksUpdateArgs} args - Arguments to update one Links.
   * @example
   * // Update one Links
   * const links = await prisma.links.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends linksUpdateArgs>(args: Prisma.SelectSubset<T, linksUpdateArgs<ExtArgs>>): Prisma.Prisma__linksClient<runtime.Types.Result.GetResult<Prisma.$linksPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Links.
   * @param {linksDeleteManyArgs} args - Arguments to filter Links to delete.
   * @example
   * // Delete a few Links
   * const { count } = await prisma.links.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends linksDeleteManyArgs>(args?: Prisma.SelectSubset<T, linksDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Links.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {linksUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Links
   * const links = await prisma.links.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends linksUpdateManyArgs>(args: Prisma.SelectSubset<T, linksUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Links and returns the data updated in the database.
   * @param {linksUpdateManyAndReturnArgs} args - Arguments to update many Links.
   * @example
   * // Update many Links
   * const links = await prisma.links.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Links and only return the `id`
   * const linksWithIdOnly = await prisma.links.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends linksUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, linksUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$linksPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Links.
   * @param {linksUpsertArgs} args - Arguments to update or create a Links.
   * @example
   * // Update or create a Links
   * const links = await prisma.links.upsert({
   *   create: {
   *     // ... data to create a Links
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Links we want to update
   *   }
   * })
   */
  upsert<T extends linksUpsertArgs>(args: Prisma.SelectSubset<T, linksUpsertArgs<ExtArgs>>): Prisma.Prisma__linksClient<runtime.Types.Result.GetResult<Prisma.$linksPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Links.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {linksCountArgs} args - Arguments to filter Links to count.
   * @example
   * // Count the number of Links
   * const count = await prisma.links.count({
   *   where: {
   *     // ... the filter for the Links we want to count
   *   }
   * })
  **/
  count<T extends linksCountArgs>(
    args?: Prisma.Subset<T, linksCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LinksCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Links.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LinksAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LinksAggregateArgs>(args: Prisma.Subset<T, LinksAggregateArgs>): Prisma.PrismaPromise<GetLinksAggregateType<T>>

  /**
   * Group by Links.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {linksGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends linksGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: linksGroupByArgs['orderBy'] }
      : { orderBy?: linksGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, linksGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLinksGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the links model
 */
readonly fields: linksFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for links.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__linksClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  profile<T extends Prisma.ProfileDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProfileDefaultArgs<ExtArgs>>): Prisma.Prisma__ProfileClient<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the links model
 */
export interface linksFieldRefs {
  readonly id: Prisma.FieldRef<"links", 'String'>
  readonly type: Prisma.FieldRef<"links", 'LinkType'>
  readonly label: Prisma.FieldRef<"links", 'String'>
  readonly url: Prisma.FieldRef<"links", 'String'>
  readonly profileId: Prisma.FieldRef<"links", 'String'>
  readonly createdAt: Prisma.FieldRef<"links", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"links", 'DateTime'>
}
    

// Custom InputTypes
/**
 * links findUnique
 */
export type linksFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the links
   */
  select?: Prisma.linksSelect<ExtArgs> | null
  /**
   * Omit specific fields from the links
   */
  omit?: Prisma.linksOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.linksInclude<ExtArgs> | null
  /**
   * Filter, which links to fetch.
   */
  where: Prisma.linksWhereUniqueInput
}

/**
 * links findUniqueOrThrow
 */
export type linksFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the links
   */
  select?: Prisma.linksSelect<ExtArgs> | null
  /**
   * Omit specific fields from the links
   */
  omit?: Prisma.linksOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.linksInclude<ExtArgs> | null
  /**
   * Filter, which links to fetch.
   */
  where: Prisma.linksWhereUniqueInput
}

/**
 * links findFirst
 */
export type linksFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the links
   */
  select?: Prisma.linksSelect<ExtArgs> | null
  /**
   * Omit specific fields from the links
   */
  omit?: Prisma.linksOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.linksInclude<ExtArgs> | null
  /**
   * Filter, which links to fetch.
   */
  where?: Prisma.linksWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of links to fetch.
   */
  orderBy?: Prisma.linksOrderByWithRelationInput | Prisma.linksOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for links.
   */
  cursor?: Prisma.linksWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` links from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` links.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of links.
   */
  distinct?: Prisma.LinksScalarFieldEnum | Prisma.LinksScalarFieldEnum[]
}

/**
 * links findFirstOrThrow
 */
export type linksFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the links
   */
  select?: Prisma.linksSelect<ExtArgs> | null
  /**
   * Omit specific fields from the links
   */
  omit?: Prisma.linksOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.linksInclude<ExtArgs> | null
  /**
   * Filter, which links to fetch.
   */
  where?: Prisma.linksWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of links to fetch.
   */
  orderBy?: Prisma.linksOrderByWithRelationInput | Prisma.linksOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for links.
   */
  cursor?: Prisma.linksWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` links from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` links.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of links.
   */
  distinct?: Prisma.LinksScalarFieldEnum | Prisma.LinksScalarFieldEnum[]
}

/**
 * links findMany
 */
export type linksFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the links
   */
  select?: Prisma.linksSelect<ExtArgs> | null
  /**
   * Omit specific fields from the links
   */
  omit?: Prisma.linksOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.linksInclude<ExtArgs> | null
  /**
   * Filter, which links to fetch.
   */
  where?: Prisma.linksWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of links to fetch.
   */
  orderBy?: Prisma.linksOrderByWithRelationInput | Prisma.linksOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing links.
   */
  cursor?: Prisma.linksWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` links from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` links.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of links.
   */
  distinct?: Prisma.LinksScalarFieldEnum | Prisma.LinksScalarFieldEnum[]
}

/**
 * links create
 */
export type linksCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the links
   */
  select?: Prisma.linksSelect<ExtArgs> | null
  /**
   * Omit specific fields from the links
   */
  omit?: Prisma.linksOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.linksInclude<ExtArgs> | null
  /**
   * The data needed to create a links.
   */
  data: Prisma.XOR<Prisma.linksCreateInput, Prisma.linksUncheckedCreateInput>
}

/**
 * links createMany
 */
export type linksCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many links.
   */
  data: Prisma.linksCreateManyInput | Prisma.linksCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * links createManyAndReturn
 */
export type linksCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the links
   */
  select?: Prisma.linksSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the links
   */
  omit?: Prisma.linksOmit<ExtArgs> | null
  /**
   * The data used to create many links.
   */
  data: Prisma.linksCreateManyInput | Prisma.linksCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.linksIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * links update
 */
export type linksUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the links
   */
  select?: Prisma.linksSelect<ExtArgs> | null
  /**
   * Omit specific fields from the links
   */
  omit?: Prisma.linksOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.linksInclude<ExtArgs> | null
  /**
   * The data needed to update a links.
   */
  data: Prisma.XOR<Prisma.linksUpdateInput, Prisma.linksUncheckedUpdateInput>
  /**
   * Choose, which links to update.
   */
  where: Prisma.linksWhereUniqueInput
}

/**
 * links updateMany
 */
export type linksUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update links.
   */
  data: Prisma.XOR<Prisma.linksUpdateManyMutationInput, Prisma.linksUncheckedUpdateManyInput>
  /**
   * Filter which links to update
   */
  where?: Prisma.linksWhereInput
  /**
   * Limit how many links to update.
   */
  limit?: number
}

/**
 * links updateManyAndReturn
 */
export type linksUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the links
   */
  select?: Prisma.linksSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the links
   */
  omit?: Prisma.linksOmit<ExtArgs> | null
  /**
   * The data used to update links.
   */
  data: Prisma.XOR<Prisma.linksUpdateManyMutationInput, Prisma.linksUncheckedUpdateManyInput>
  /**
   * Filter which links to update
   */
  where?: Prisma.linksWhereInput
  /**
   * Limit how many links to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.linksIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * links upsert
 */
export type linksUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the links
   */
  select?: Prisma.linksSelect<ExtArgs> | null
  /**
   * Omit specific fields from the links
   */
  omit?: Prisma.linksOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.linksInclude<ExtArgs> | null
  /**
   * The filter to search for the links to update in case it exists.
   */
  where: Prisma.linksWhereUniqueInput
  /**
   * In case the links found by the `where` argument doesn't exist, create a new links with this data.
   */
  create: Prisma.XOR<Prisma.linksCreateInput, Prisma.linksUncheckedCreateInput>
  /**
   * In case the links was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.linksUpdateInput, Prisma.linksUncheckedUpdateInput>
}

/**
 * links delete
 */
export type linksDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the links
   */
  select?: Prisma.linksSelect<ExtArgs> | null
  /**
   * Omit specific fields from the links
   */
  omit?: Prisma.linksOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.linksInclude<ExtArgs> | null
  /**
   * Filter which links to delete.
   */
  where: Prisma.linksWhereUniqueInput
}

/**
 * links deleteMany
 */
export type linksDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which links to delete
   */
  where?: Prisma.linksWhereInput
  /**
   * Limit how many links to delete.
   */
  limit?: number
}

/**
 * links without action
 */
export type linksDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the links
   */
  select?: Prisma.linksSelect<ExtArgs> | null
  /**
   * Omit specific fields from the links
   */
  omit?: Prisma.linksOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.linksInclude<ExtArgs> | null
}
