
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Profile` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Profile
 * 
 */
export type ProfileModel = runtime.Types.Result.DefaultSelection<Prisma.$ProfilePayload>

export type AggregateProfile = {
  _count: ProfileCountAggregateOutputType | null
  _avg: ProfileAvgAggregateOutputType | null
  _sum: ProfileSumAggregateOutputType | null
  _min: ProfileMinAggregateOutputType | null
  _max: ProfileMaxAggregateOutputType | null
}

export type ProfileAvgAggregateOutputType = {
  age: number | null
  views: number | null
}

export type ProfileSumAggregateOutputType = {
  age: number | null
  views: number | null
}

export type ProfileMinAggregateOutputType = {
  id: string | null
  avatar: string | null
  banner: string | null
  name: string | null
  email: string | null
  age: number | null
  location: string | null
  userId: string | null
  username: string | null
  bio: string | null
  github: string | null
  twitter: string | null
  linkedin: string | null
  themeId: string | null
  resume: string | null
  tagline: string | null
  bookAcall: string | null
  views: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ProfileMaxAggregateOutputType = {
  id: string | null
  avatar: string | null
  banner: string | null
  name: string | null
  email: string | null
  age: number | null
  location: string | null
  userId: string | null
  username: string | null
  bio: string | null
  github: string | null
  twitter: string | null
  linkedin: string | null
  themeId: string | null
  resume: string | null
  tagline: string | null
  bookAcall: string | null
  views: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ProfileCountAggregateOutputType = {
  id: number
  avatar: number
  banner: number
  name: number
  email: number
  age: number
  location: number
  userId: number
  username: number
  bio: number
  skills: number
  github: number
  twitter: number
  linkedin: number
  themeId: number
  resume: number
  tagline: number
  bookAcall: number
  views: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ProfileAvgAggregateInputType = {
  age?: true
  views?: true
}

export type ProfileSumAggregateInputType = {
  age?: true
  views?: true
}

export type ProfileMinAggregateInputType = {
  id?: true
  avatar?: true
  banner?: true
  name?: true
  email?: true
  age?: true
  location?: true
  userId?: true
  username?: true
  bio?: true
  github?: true
  twitter?: true
  linkedin?: true
  themeId?: true
  resume?: true
  tagline?: true
  bookAcall?: true
  views?: true
  createdAt?: true
  updatedAt?: true
}

export type ProfileMaxAggregateInputType = {
  id?: true
  avatar?: true
  banner?: true
  name?: true
  email?: true
  age?: true
  location?: true
  userId?: true
  username?: true
  bio?: true
  github?: true
  twitter?: true
  linkedin?: true
  themeId?: true
  resume?: true
  tagline?: true
  bookAcall?: true
  views?: true
  createdAt?: true
  updatedAt?: true
}

export type ProfileCountAggregateInputType = {
  id?: true
  avatar?: true
  banner?: true
  name?: true
  email?: true
  age?: true
  location?: true
  userId?: true
  username?: true
  bio?: true
  skills?: true
  github?: true
  twitter?: true
  linkedin?: true
  themeId?: true
  resume?: true
  tagline?: true
  bookAcall?: true
  views?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ProfileAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Profile to aggregate.
   */
  where?: Prisma.ProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Profiles to fetch.
   */
  orderBy?: Prisma.ProfileOrderByWithRelationInput | Prisma.ProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Profiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Profiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Profiles
  **/
  _count?: true | ProfileCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ProfileAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ProfileSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProfileMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProfileMaxAggregateInputType
}

export type GetProfileAggregateType<T extends ProfileAggregateArgs> = {
      [P in keyof T & keyof AggregateProfile]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProfile[P]>
    : Prisma.GetScalarType<T[P], AggregateProfile[P]>
}




export type ProfileGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProfileWhereInput
  orderBy?: Prisma.ProfileOrderByWithAggregationInput | Prisma.ProfileOrderByWithAggregationInput[]
  by: Prisma.ProfileScalarFieldEnum[] | Prisma.ProfileScalarFieldEnum
  having?: Prisma.ProfileScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProfileCountAggregateInputType | true
  _avg?: ProfileAvgAggregateInputType
  _sum?: ProfileSumAggregateInputType
  _min?: ProfileMinAggregateInputType
  _max?: ProfileMaxAggregateInputType
}

export type ProfileGroupByOutputType = {
  id: string
  avatar: string | null
  banner: string | null
  name: string | null
  email: string | null
  age: number | null
  location: string | null
  userId: string
  username: string | null
  bio: string | null
  skills: string[]
  github: string | null
  twitter: string | null
  linkedin: string | null
  themeId: string
  resume: string | null
  tagline: string | null
  bookAcall: string | null
  views: number
  createdAt: Date
  updatedAt: Date
  _count: ProfileCountAggregateOutputType | null
  _avg: ProfileAvgAggregateOutputType | null
  _sum: ProfileSumAggregateOutputType | null
  _min: ProfileMinAggregateOutputType | null
  _max: ProfileMaxAggregateOutputType | null
}

type GetProfileGroupByPayload<T extends ProfileGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProfileGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProfileGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProfileGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProfileGroupByOutputType[P]>
      }
    >
  >



export type ProfileWhereInput = {
  AND?: Prisma.ProfileWhereInput | Prisma.ProfileWhereInput[]
  OR?: Prisma.ProfileWhereInput[]
  NOT?: Prisma.ProfileWhereInput | Prisma.ProfileWhereInput[]
  id?: Prisma.StringFilter<"Profile"> | string
  avatar?: Prisma.StringNullableFilter<"Profile"> | string | null
  banner?: Prisma.StringNullableFilter<"Profile"> | string | null
  name?: Prisma.StringNullableFilter<"Profile"> | string | null
  email?: Prisma.StringNullableFilter<"Profile"> | string | null
  age?: Prisma.IntNullableFilter<"Profile"> | number | null
  location?: Prisma.StringNullableFilter<"Profile"> | string | null
  userId?: Prisma.StringFilter<"Profile"> | string
  username?: Prisma.StringNullableFilter<"Profile"> | string | null
  bio?: Prisma.StringNullableFilter<"Profile"> | string | null
  skills?: Prisma.StringNullableListFilter<"Profile">
  github?: Prisma.StringNullableFilter<"Profile"> | string | null
  twitter?: Prisma.StringNullableFilter<"Profile"> | string | null
  linkedin?: Prisma.StringNullableFilter<"Profile"> | string | null
  themeId?: Prisma.StringFilter<"Profile"> | string
  resume?: Prisma.StringNullableFilter<"Profile"> | string | null
  tagline?: Prisma.StringNullableFilter<"Profile"> | string | null
  bookAcall?: Prisma.StringNullableFilter<"Profile"> | string | null
  views?: Prisma.IntFilter<"Profile"> | number
  createdAt?: Prisma.DateTimeFilter<"Profile"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Profile"> | Date | string
  experiences?: Prisma.ExperienceListRelationFilter
  projects?: Prisma.ProjectListRelationFilter
  blogs?: Prisma.BlogListRelationFilter
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type ProfileOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  avatar?: Prisma.SortOrderInput | Prisma.SortOrder
  banner?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  age?: Prisma.SortOrderInput | Prisma.SortOrder
  location?: Prisma.SortOrderInput | Prisma.SortOrder
  userId?: Prisma.SortOrder
  username?: Prisma.SortOrderInput | Prisma.SortOrder
  bio?: Prisma.SortOrderInput | Prisma.SortOrder
  skills?: Prisma.SortOrder
  github?: Prisma.SortOrderInput | Prisma.SortOrder
  twitter?: Prisma.SortOrderInput | Prisma.SortOrder
  linkedin?: Prisma.SortOrderInput | Prisma.SortOrder
  themeId?: Prisma.SortOrder
  resume?: Prisma.SortOrderInput | Prisma.SortOrder
  tagline?: Prisma.SortOrderInput | Prisma.SortOrder
  bookAcall?: Prisma.SortOrderInput | Prisma.SortOrder
  views?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  experiences?: Prisma.ExperienceOrderByRelationAggregateInput
  projects?: Prisma.ProjectOrderByRelationAggregateInput
  blogs?: Prisma.BlogOrderByRelationAggregateInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type ProfileWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId?: string
  username?: string
  AND?: Prisma.ProfileWhereInput | Prisma.ProfileWhereInput[]
  OR?: Prisma.ProfileWhereInput[]
  NOT?: Prisma.ProfileWhereInput | Prisma.ProfileWhereInput[]
  avatar?: Prisma.StringNullableFilter<"Profile"> | string | null
  banner?: Prisma.StringNullableFilter<"Profile"> | string | null
  name?: Prisma.StringNullableFilter<"Profile"> | string | null
  email?: Prisma.StringNullableFilter<"Profile"> | string | null
  age?: Prisma.IntNullableFilter<"Profile"> | number | null
  location?: Prisma.StringNullableFilter<"Profile"> | string | null
  bio?: Prisma.StringNullableFilter<"Profile"> | string | null
  skills?: Prisma.StringNullableListFilter<"Profile">
  github?: Prisma.StringNullableFilter<"Profile"> | string | null
  twitter?: Prisma.StringNullableFilter<"Profile"> | string | null
  linkedin?: Prisma.StringNullableFilter<"Profile"> | string | null
  themeId?: Prisma.StringFilter<"Profile"> | string
  resume?: Prisma.StringNullableFilter<"Profile"> | string | null
  tagline?: Prisma.StringNullableFilter<"Profile"> | string | null
  bookAcall?: Prisma.StringNullableFilter<"Profile"> | string | null
  views?: Prisma.IntFilter<"Profile"> | number
  createdAt?: Prisma.DateTimeFilter<"Profile"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Profile"> | Date | string
  experiences?: Prisma.ExperienceListRelationFilter
  projects?: Prisma.ProjectListRelationFilter
  blogs?: Prisma.BlogListRelationFilter
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "userId" | "username">

export type ProfileOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  avatar?: Prisma.SortOrderInput | Prisma.SortOrder
  banner?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  age?: Prisma.SortOrderInput | Prisma.SortOrder
  location?: Prisma.SortOrderInput | Prisma.SortOrder
  userId?: Prisma.SortOrder
  username?: Prisma.SortOrderInput | Prisma.SortOrder
  bio?: Prisma.SortOrderInput | Prisma.SortOrder
  skills?: Prisma.SortOrder
  github?: Prisma.SortOrderInput | Prisma.SortOrder
  twitter?: Prisma.SortOrderInput | Prisma.SortOrder
  linkedin?: Prisma.SortOrderInput | Prisma.SortOrder
  themeId?: Prisma.SortOrder
  resume?: Prisma.SortOrderInput | Prisma.SortOrder
  tagline?: Prisma.SortOrderInput | Prisma.SortOrder
  bookAcall?: Prisma.SortOrderInput | Prisma.SortOrder
  views?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ProfileCountOrderByAggregateInput
  _avg?: Prisma.ProfileAvgOrderByAggregateInput
  _max?: Prisma.ProfileMaxOrderByAggregateInput
  _min?: Prisma.ProfileMinOrderByAggregateInput
  _sum?: Prisma.ProfileSumOrderByAggregateInput
}

export type ProfileScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProfileScalarWhereWithAggregatesInput | Prisma.ProfileScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProfileScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProfileScalarWhereWithAggregatesInput | Prisma.ProfileScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Profile"> | string
  avatar?: Prisma.StringNullableWithAggregatesFilter<"Profile"> | string | null
  banner?: Prisma.StringNullableWithAggregatesFilter<"Profile"> | string | null
  name?: Prisma.StringNullableWithAggregatesFilter<"Profile"> | string | null
  email?: Prisma.StringNullableWithAggregatesFilter<"Profile"> | string | null
  age?: Prisma.IntNullableWithAggregatesFilter<"Profile"> | number | null
  location?: Prisma.StringNullableWithAggregatesFilter<"Profile"> | string | null
  userId?: Prisma.StringWithAggregatesFilter<"Profile"> | string
  username?: Prisma.StringNullableWithAggregatesFilter<"Profile"> | string | null
  bio?: Prisma.StringNullableWithAggregatesFilter<"Profile"> | string | null
  skills?: Prisma.StringNullableListFilter<"Profile">
  github?: Prisma.StringNullableWithAggregatesFilter<"Profile"> | string | null
  twitter?: Prisma.StringNullableWithAggregatesFilter<"Profile"> | string | null
  linkedin?: Prisma.StringNullableWithAggregatesFilter<"Profile"> | string | null
  themeId?: Prisma.StringWithAggregatesFilter<"Profile"> | string
  resume?: Prisma.StringNullableWithAggregatesFilter<"Profile"> | string | null
  tagline?: Prisma.StringNullableWithAggregatesFilter<"Profile"> | string | null
  bookAcall?: Prisma.StringNullableWithAggregatesFilter<"Profile"> | string | null
  views?: Prisma.IntWithAggregatesFilter<"Profile"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Profile"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Profile"> | Date | string
}

export type ProfileCreateInput = {
  id?: string
  avatar?: string | null
  banner?: string | null
  name?: string | null
  email?: string | null
  age?: number | null
  location?: string | null
  username?: string | null
  bio?: string | null
  skills?: Prisma.ProfileCreateskillsInput | string[]
  github?: string | null
  twitter?: string | null
  linkedin?: string | null
  themeId?: string
  resume?: string | null
  tagline?: string | null
  bookAcall?: string | null
  views?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  experiences?: Prisma.ExperienceCreateNestedManyWithoutProfileInput
  projects?: Prisma.ProjectCreateNestedManyWithoutProfileInput
  blogs?: Prisma.BlogCreateNestedManyWithoutProfileInput
  user: Prisma.UserCreateNestedOneWithoutProfileInput
}

export type ProfileUncheckedCreateInput = {
  id?: string
  avatar?: string | null
  banner?: string | null
  name?: string | null
  email?: string | null
  age?: number | null
  location?: string | null
  userId: string
  username?: string | null
  bio?: string | null
  skills?: Prisma.ProfileCreateskillsInput | string[]
  github?: string | null
  twitter?: string | null
  linkedin?: string | null
  themeId?: string
  resume?: string | null
  tagline?: string | null
  bookAcall?: string | null
  views?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  experiences?: Prisma.ExperienceUncheckedCreateNestedManyWithoutProfileInput
  projects?: Prisma.ProjectUncheckedCreateNestedManyWithoutProfileInput
  blogs?: Prisma.BlogUncheckedCreateNestedManyWithoutProfileInput
}

export type ProfileUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  banner?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  age?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  skills?: Prisma.ProfileUpdateskillsInput | string[]
  github?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  twitter?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  linkedin?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  themeId?: Prisma.StringFieldUpdateOperationsInput | string
  resume?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tagline?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bookAcall?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  views?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  experiences?: Prisma.ExperienceUpdateManyWithoutProfileNestedInput
  projects?: Prisma.ProjectUpdateManyWithoutProfileNestedInput
  blogs?: Prisma.BlogUpdateManyWithoutProfileNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutProfileNestedInput
}

export type ProfileUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  banner?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  age?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  skills?: Prisma.ProfileUpdateskillsInput | string[]
  github?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  twitter?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  linkedin?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  themeId?: Prisma.StringFieldUpdateOperationsInput | string
  resume?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tagline?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bookAcall?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  views?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  experiences?: Prisma.ExperienceUncheckedUpdateManyWithoutProfileNestedInput
  projects?: Prisma.ProjectUncheckedUpdateManyWithoutProfileNestedInput
  blogs?: Prisma.BlogUncheckedUpdateManyWithoutProfileNestedInput
}

export type ProfileCreateManyInput = {
  id?: string
  avatar?: string | null
  banner?: string | null
  name?: string | null
  email?: string | null
  age?: number | null
  location?: string | null
  userId: string
  username?: string | null
  bio?: string | null
  skills?: Prisma.ProfileCreateskillsInput | string[]
  github?: string | null
  twitter?: string | null
  linkedin?: string | null
  themeId?: string
  resume?: string | null
  tagline?: string | null
  bookAcall?: string | null
  views?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProfileUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  banner?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  age?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  skills?: Prisma.ProfileUpdateskillsInput | string[]
  github?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  twitter?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  linkedin?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  themeId?: Prisma.StringFieldUpdateOperationsInput | string
  resume?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tagline?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bookAcall?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  views?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProfileUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  banner?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  age?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  skills?: Prisma.ProfileUpdateskillsInput | string[]
  github?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  twitter?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  linkedin?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  themeId?: Prisma.StringFieldUpdateOperationsInput | string
  resume?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tagline?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bookAcall?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  views?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProfileNullableScalarRelationFilter = {
  is?: Prisma.ProfileWhereInput | null
  isNot?: Prisma.ProfileWhereInput | null
}

export type StringNullableListFilter<$PrismaModel = never> = {
  equals?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  has?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  hasEvery?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  hasSome?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  isEmpty?: boolean
}

export type ProfileCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  avatar?: Prisma.SortOrder
  banner?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  age?: Prisma.SortOrder
  location?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  username?: Prisma.SortOrder
  bio?: Prisma.SortOrder
  skills?: Prisma.SortOrder
  github?: Prisma.SortOrder
  twitter?: Prisma.SortOrder
  linkedin?: Prisma.SortOrder
  themeId?: Prisma.SortOrder
  resume?: Prisma.SortOrder
  tagline?: Prisma.SortOrder
  bookAcall?: Prisma.SortOrder
  views?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProfileAvgOrderByAggregateInput = {
  age?: Prisma.SortOrder
  views?: Prisma.SortOrder
}

export type ProfileMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  avatar?: Prisma.SortOrder
  banner?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  age?: Prisma.SortOrder
  location?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  username?: Prisma.SortOrder
  bio?: Prisma.SortOrder
  github?: Prisma.SortOrder
  twitter?: Prisma.SortOrder
  linkedin?: Prisma.SortOrder
  themeId?: Prisma.SortOrder
  resume?: Prisma.SortOrder
  tagline?: Prisma.SortOrder
  bookAcall?: Prisma.SortOrder
  views?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProfileMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  avatar?: Prisma.SortOrder
  banner?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  age?: Prisma.SortOrder
  location?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  username?: Prisma.SortOrder
  bio?: Prisma.SortOrder
  github?: Prisma.SortOrder
  twitter?: Prisma.SortOrder
  linkedin?: Prisma.SortOrder
  themeId?: Prisma.SortOrder
  resume?: Prisma.SortOrder
  tagline?: Prisma.SortOrder
  bookAcall?: Prisma.SortOrder
  views?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProfileSumOrderByAggregateInput = {
  age?: Prisma.SortOrder
  views?: Prisma.SortOrder
}

export type ProfileCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ProfileCreateWithoutUserInput, Prisma.ProfileUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.ProfileCreateOrConnectWithoutUserInput
  connect?: Prisma.ProfileWhereUniqueInput
}

export type ProfileUncheckedCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ProfileCreateWithoutUserInput, Prisma.ProfileUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.ProfileCreateOrConnectWithoutUserInput
  connect?: Prisma.ProfileWhereUniqueInput
}

export type ProfileUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ProfileCreateWithoutUserInput, Prisma.ProfileUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.ProfileCreateOrConnectWithoutUserInput
  upsert?: Prisma.ProfileUpsertWithoutUserInput
  disconnect?: Prisma.ProfileWhereInput | boolean
  delete?: Prisma.ProfileWhereInput | boolean
  connect?: Prisma.ProfileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProfileUpdateToOneWithWhereWithoutUserInput, Prisma.ProfileUpdateWithoutUserInput>, Prisma.ProfileUncheckedUpdateWithoutUserInput>
}

export type ProfileUncheckedUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ProfileCreateWithoutUserInput, Prisma.ProfileUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.ProfileCreateOrConnectWithoutUserInput
  upsert?: Prisma.ProfileUpsertWithoutUserInput
  disconnect?: Prisma.ProfileWhereInput | boolean
  delete?: Prisma.ProfileWhereInput | boolean
  connect?: Prisma.ProfileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProfileUpdateToOneWithWhereWithoutUserInput, Prisma.ProfileUpdateWithoutUserInput>, Prisma.ProfileUncheckedUpdateWithoutUserInput>
}

export type ProfileCreateskillsInput = {
  set: string[]
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type ProfileUpdateskillsInput = {
  set?: string[]
  push?: string | string[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type ProfileCreateNestedOneWithoutExperiencesInput = {
  create?: Prisma.XOR<Prisma.ProfileCreateWithoutExperiencesInput, Prisma.ProfileUncheckedCreateWithoutExperiencesInput>
  connectOrCreate?: Prisma.ProfileCreateOrConnectWithoutExperiencesInput
  connect?: Prisma.ProfileWhereUniqueInput
}

export type ProfileUpdateOneWithoutExperiencesNestedInput = {
  create?: Prisma.XOR<Prisma.ProfileCreateWithoutExperiencesInput, Prisma.ProfileUncheckedCreateWithoutExperiencesInput>
  connectOrCreate?: Prisma.ProfileCreateOrConnectWithoutExperiencesInput
  upsert?: Prisma.ProfileUpsertWithoutExperiencesInput
  disconnect?: Prisma.ProfileWhereInput | boolean
  delete?: Prisma.ProfileWhereInput | boolean
  connect?: Prisma.ProfileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProfileUpdateToOneWithWhereWithoutExperiencesInput, Prisma.ProfileUpdateWithoutExperiencesInput>, Prisma.ProfileUncheckedUpdateWithoutExperiencesInput>
}

export type ProfileCreateNestedOneWithoutProjectsInput = {
  create?: Prisma.XOR<Prisma.ProfileCreateWithoutProjectsInput, Prisma.ProfileUncheckedCreateWithoutProjectsInput>
  connectOrCreate?: Prisma.ProfileCreateOrConnectWithoutProjectsInput
  connect?: Prisma.ProfileWhereUniqueInput
}

export type ProfileUpdateOneWithoutProjectsNestedInput = {
  create?: Prisma.XOR<Prisma.ProfileCreateWithoutProjectsInput, Prisma.ProfileUncheckedCreateWithoutProjectsInput>
  connectOrCreate?: Prisma.ProfileCreateOrConnectWithoutProjectsInput
  upsert?: Prisma.ProfileUpsertWithoutProjectsInput
  disconnect?: Prisma.ProfileWhereInput | boolean
  delete?: Prisma.ProfileWhereInput | boolean
  connect?: Prisma.ProfileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProfileUpdateToOneWithWhereWithoutProjectsInput, Prisma.ProfileUpdateWithoutProjectsInput>, Prisma.ProfileUncheckedUpdateWithoutProjectsInput>
}

export type ProfileCreateNestedOneWithoutBlogsInput = {
  create?: Prisma.XOR<Prisma.ProfileCreateWithoutBlogsInput, Prisma.ProfileUncheckedCreateWithoutBlogsInput>
  connectOrCreate?: Prisma.ProfileCreateOrConnectWithoutBlogsInput
  connect?: Prisma.ProfileWhereUniqueInput
}

export type ProfileUpdateOneWithoutBlogsNestedInput = {
  create?: Prisma.XOR<Prisma.ProfileCreateWithoutBlogsInput, Prisma.ProfileUncheckedCreateWithoutBlogsInput>
  connectOrCreate?: Prisma.ProfileCreateOrConnectWithoutBlogsInput
  upsert?: Prisma.ProfileUpsertWithoutBlogsInput
  disconnect?: Prisma.ProfileWhereInput | boolean
  delete?: Prisma.ProfileWhereInput | boolean
  connect?: Prisma.ProfileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProfileUpdateToOneWithWhereWithoutBlogsInput, Prisma.ProfileUpdateWithoutBlogsInput>, Prisma.ProfileUncheckedUpdateWithoutBlogsInput>
}

export type ProfileCreateWithoutUserInput = {
  id?: string
  avatar?: string | null
  banner?: string | null
  name?: string | null
  email?: string | null
  age?: number | null
  location?: string | null
  username?: string | null
  bio?: string | null
  skills?: Prisma.ProfileCreateskillsInput | string[]
  github?: string | null
  twitter?: string | null
  linkedin?: string | null
  themeId?: string
  resume?: string | null
  tagline?: string | null
  bookAcall?: string | null
  views?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  experiences?: Prisma.ExperienceCreateNestedManyWithoutProfileInput
  projects?: Prisma.ProjectCreateNestedManyWithoutProfileInput
  blogs?: Prisma.BlogCreateNestedManyWithoutProfileInput
}

export type ProfileUncheckedCreateWithoutUserInput = {
  id?: string
  avatar?: string | null
  banner?: string | null
  name?: string | null
  email?: string | null
  age?: number | null
  location?: string | null
  username?: string | null
  bio?: string | null
  skills?: Prisma.ProfileCreateskillsInput | string[]
  github?: string | null
  twitter?: string | null
  linkedin?: string | null
  themeId?: string
  resume?: string | null
  tagline?: string | null
  bookAcall?: string | null
  views?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  experiences?: Prisma.ExperienceUncheckedCreateNestedManyWithoutProfileInput
  projects?: Prisma.ProjectUncheckedCreateNestedManyWithoutProfileInput
  blogs?: Prisma.BlogUncheckedCreateNestedManyWithoutProfileInput
}

export type ProfileCreateOrConnectWithoutUserInput = {
  where: Prisma.ProfileWhereUniqueInput
  create: Prisma.XOR<Prisma.ProfileCreateWithoutUserInput, Prisma.ProfileUncheckedCreateWithoutUserInput>
}

export type ProfileUpsertWithoutUserInput = {
  update: Prisma.XOR<Prisma.ProfileUpdateWithoutUserInput, Prisma.ProfileUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.ProfileCreateWithoutUserInput, Prisma.ProfileUncheckedCreateWithoutUserInput>
  where?: Prisma.ProfileWhereInput
}

export type ProfileUpdateToOneWithWhereWithoutUserInput = {
  where?: Prisma.ProfileWhereInput
  data: Prisma.XOR<Prisma.ProfileUpdateWithoutUserInput, Prisma.ProfileUncheckedUpdateWithoutUserInput>
}

export type ProfileUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  banner?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  age?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  skills?: Prisma.ProfileUpdateskillsInput | string[]
  github?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  twitter?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  linkedin?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  themeId?: Prisma.StringFieldUpdateOperationsInput | string
  resume?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tagline?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bookAcall?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  views?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  experiences?: Prisma.ExperienceUpdateManyWithoutProfileNestedInput
  projects?: Prisma.ProjectUpdateManyWithoutProfileNestedInput
  blogs?: Prisma.BlogUpdateManyWithoutProfileNestedInput
}

export type ProfileUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  banner?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  age?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  skills?: Prisma.ProfileUpdateskillsInput | string[]
  github?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  twitter?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  linkedin?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  themeId?: Prisma.StringFieldUpdateOperationsInput | string
  resume?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tagline?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bookAcall?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  views?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  experiences?: Prisma.ExperienceUncheckedUpdateManyWithoutProfileNestedInput
  projects?: Prisma.ProjectUncheckedUpdateManyWithoutProfileNestedInput
  blogs?: Prisma.BlogUncheckedUpdateManyWithoutProfileNestedInput
}

export type ProfileCreateWithoutExperiencesInput = {
  id?: string
  avatar?: string | null
  banner?: string | null
  name?: string | null
  email?: string | null
  age?: number | null
  location?: string | null
  username?: string | null
  bio?: string | null
  skills?: Prisma.ProfileCreateskillsInput | string[]
  github?: string | null
  twitter?: string | null
  linkedin?: string | null
  themeId?: string
  resume?: string | null
  tagline?: string | null
  bookAcall?: string | null
  views?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  projects?: Prisma.ProjectCreateNestedManyWithoutProfileInput
  blogs?: Prisma.BlogCreateNestedManyWithoutProfileInput
  user: Prisma.UserCreateNestedOneWithoutProfileInput
}

export type ProfileUncheckedCreateWithoutExperiencesInput = {
  id?: string
  avatar?: string | null
  banner?: string | null
  name?: string | null
  email?: string | null
  age?: number | null
  location?: string | null
  userId: string
  username?: string | null
  bio?: string | null
  skills?: Prisma.ProfileCreateskillsInput | string[]
  github?: string | null
  twitter?: string | null
  linkedin?: string | null
  themeId?: string
  resume?: string | null
  tagline?: string | null
  bookAcall?: string | null
  views?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  projects?: Prisma.ProjectUncheckedCreateNestedManyWithoutProfileInput
  blogs?: Prisma.BlogUncheckedCreateNestedManyWithoutProfileInput
}

export type ProfileCreateOrConnectWithoutExperiencesInput = {
  where: Prisma.ProfileWhereUniqueInput
  create: Prisma.XOR<Prisma.ProfileCreateWithoutExperiencesInput, Prisma.ProfileUncheckedCreateWithoutExperiencesInput>
}

export type ProfileUpsertWithoutExperiencesInput = {
  update: Prisma.XOR<Prisma.ProfileUpdateWithoutExperiencesInput, Prisma.ProfileUncheckedUpdateWithoutExperiencesInput>
  create: Prisma.XOR<Prisma.ProfileCreateWithoutExperiencesInput, Prisma.ProfileUncheckedCreateWithoutExperiencesInput>
  where?: Prisma.ProfileWhereInput
}

export type ProfileUpdateToOneWithWhereWithoutExperiencesInput = {
  where?: Prisma.ProfileWhereInput
  data: Prisma.XOR<Prisma.ProfileUpdateWithoutExperiencesInput, Prisma.ProfileUncheckedUpdateWithoutExperiencesInput>
}

export type ProfileUpdateWithoutExperiencesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  banner?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  age?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  skills?: Prisma.ProfileUpdateskillsInput | string[]
  github?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  twitter?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  linkedin?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  themeId?: Prisma.StringFieldUpdateOperationsInput | string
  resume?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tagline?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bookAcall?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  views?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  projects?: Prisma.ProjectUpdateManyWithoutProfileNestedInput
  blogs?: Prisma.BlogUpdateManyWithoutProfileNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutProfileNestedInput
}

export type ProfileUncheckedUpdateWithoutExperiencesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  banner?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  age?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  skills?: Prisma.ProfileUpdateskillsInput | string[]
  github?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  twitter?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  linkedin?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  themeId?: Prisma.StringFieldUpdateOperationsInput | string
  resume?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tagline?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bookAcall?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  views?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  projects?: Prisma.ProjectUncheckedUpdateManyWithoutProfileNestedInput
  blogs?: Prisma.BlogUncheckedUpdateManyWithoutProfileNestedInput
}

export type ProfileCreateWithoutProjectsInput = {
  id?: string
  avatar?: string | null
  banner?: string | null
  name?: string | null
  email?: string | null
  age?: number | null
  location?: string | null
  username?: string | null
  bio?: string | null
  skills?: Prisma.ProfileCreateskillsInput | string[]
  github?: string | null
  twitter?: string | null
  linkedin?: string | null
  themeId?: string
  resume?: string | null
  tagline?: string | null
  bookAcall?: string | null
  views?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  experiences?: Prisma.ExperienceCreateNestedManyWithoutProfileInput
  blogs?: Prisma.BlogCreateNestedManyWithoutProfileInput
  user: Prisma.UserCreateNestedOneWithoutProfileInput
}

export type ProfileUncheckedCreateWithoutProjectsInput = {
  id?: string
  avatar?: string | null
  banner?: string | null
  name?: string | null
  email?: string | null
  age?: number | null
  location?: string | null
  userId: string
  username?: string | null
  bio?: string | null
  skills?: Prisma.ProfileCreateskillsInput | string[]
  github?: string | null
  twitter?: string | null
  linkedin?: string | null
  themeId?: string
  resume?: string | null
  tagline?: string | null
  bookAcall?: string | null
  views?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  experiences?: Prisma.ExperienceUncheckedCreateNestedManyWithoutProfileInput
  blogs?: Prisma.BlogUncheckedCreateNestedManyWithoutProfileInput
}

export type ProfileCreateOrConnectWithoutProjectsInput = {
  where: Prisma.ProfileWhereUniqueInput
  create: Prisma.XOR<Prisma.ProfileCreateWithoutProjectsInput, Prisma.ProfileUncheckedCreateWithoutProjectsInput>
}

export type ProfileUpsertWithoutProjectsInput = {
  update: Prisma.XOR<Prisma.ProfileUpdateWithoutProjectsInput, Prisma.ProfileUncheckedUpdateWithoutProjectsInput>
  create: Prisma.XOR<Prisma.ProfileCreateWithoutProjectsInput, Prisma.ProfileUncheckedCreateWithoutProjectsInput>
  where?: Prisma.ProfileWhereInput
}

export type ProfileUpdateToOneWithWhereWithoutProjectsInput = {
  where?: Prisma.ProfileWhereInput
  data: Prisma.XOR<Prisma.ProfileUpdateWithoutProjectsInput, Prisma.ProfileUncheckedUpdateWithoutProjectsInput>
}

export type ProfileUpdateWithoutProjectsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  banner?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  age?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  skills?: Prisma.ProfileUpdateskillsInput | string[]
  github?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  twitter?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  linkedin?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  themeId?: Prisma.StringFieldUpdateOperationsInput | string
  resume?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tagline?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bookAcall?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  views?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  experiences?: Prisma.ExperienceUpdateManyWithoutProfileNestedInput
  blogs?: Prisma.BlogUpdateManyWithoutProfileNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutProfileNestedInput
}

export type ProfileUncheckedUpdateWithoutProjectsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  banner?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  age?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  skills?: Prisma.ProfileUpdateskillsInput | string[]
  github?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  twitter?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  linkedin?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  themeId?: Prisma.StringFieldUpdateOperationsInput | string
  resume?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tagline?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bookAcall?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  views?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  experiences?: Prisma.ExperienceUncheckedUpdateManyWithoutProfileNestedInput
  blogs?: Prisma.BlogUncheckedUpdateManyWithoutProfileNestedInput
}

export type ProfileCreateWithoutBlogsInput = {
  id?: string
  avatar?: string | null
  banner?: string | null
  name?: string | null
  email?: string | null
  age?: number | null
  location?: string | null
  username?: string | null
  bio?: string | null
  skills?: Prisma.ProfileCreateskillsInput | string[]
  github?: string | null
  twitter?: string | null
  linkedin?: string | null
  themeId?: string
  resume?: string | null
  tagline?: string | null
  bookAcall?: string | null
  views?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  experiences?: Prisma.ExperienceCreateNestedManyWithoutProfileInput
  projects?: Prisma.ProjectCreateNestedManyWithoutProfileInput
  user: Prisma.UserCreateNestedOneWithoutProfileInput
}

export type ProfileUncheckedCreateWithoutBlogsInput = {
  id?: string
  avatar?: string | null
  banner?: string | null
  name?: string | null
  email?: string | null
  age?: number | null
  location?: string | null
  userId: string
  username?: string | null
  bio?: string | null
  skills?: Prisma.ProfileCreateskillsInput | string[]
  github?: string | null
  twitter?: string | null
  linkedin?: string | null
  themeId?: string
  resume?: string | null
  tagline?: string | null
  bookAcall?: string | null
  views?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  experiences?: Prisma.ExperienceUncheckedCreateNestedManyWithoutProfileInput
  projects?: Prisma.ProjectUncheckedCreateNestedManyWithoutProfileInput
}

export type ProfileCreateOrConnectWithoutBlogsInput = {
  where: Prisma.ProfileWhereUniqueInput
  create: Prisma.XOR<Prisma.ProfileCreateWithoutBlogsInput, Prisma.ProfileUncheckedCreateWithoutBlogsInput>
}

export type ProfileUpsertWithoutBlogsInput = {
  update: Prisma.XOR<Prisma.ProfileUpdateWithoutBlogsInput, Prisma.ProfileUncheckedUpdateWithoutBlogsInput>
  create: Prisma.XOR<Prisma.ProfileCreateWithoutBlogsInput, Prisma.ProfileUncheckedCreateWithoutBlogsInput>
  where?: Prisma.ProfileWhereInput
}

export type ProfileUpdateToOneWithWhereWithoutBlogsInput = {
  where?: Prisma.ProfileWhereInput
  data: Prisma.XOR<Prisma.ProfileUpdateWithoutBlogsInput, Prisma.ProfileUncheckedUpdateWithoutBlogsInput>
}

export type ProfileUpdateWithoutBlogsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  banner?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  age?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  skills?: Prisma.ProfileUpdateskillsInput | string[]
  github?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  twitter?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  linkedin?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  themeId?: Prisma.StringFieldUpdateOperationsInput | string
  resume?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tagline?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bookAcall?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  views?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  experiences?: Prisma.ExperienceUpdateManyWithoutProfileNestedInput
  projects?: Prisma.ProjectUpdateManyWithoutProfileNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutProfileNestedInput
}

export type ProfileUncheckedUpdateWithoutBlogsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  avatar?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  banner?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  age?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  skills?: Prisma.ProfileUpdateskillsInput | string[]
  github?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  twitter?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  linkedin?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  themeId?: Prisma.StringFieldUpdateOperationsInput | string
  resume?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tagline?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bookAcall?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  views?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  experiences?: Prisma.ExperienceUncheckedUpdateManyWithoutProfileNestedInput
  projects?: Prisma.ProjectUncheckedUpdateManyWithoutProfileNestedInput
}


/**
 * Count Type ProfileCountOutputType
 */

export type ProfileCountOutputType = {
  experiences: number
  projects: number
  blogs: number
}

export type ProfileCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  experiences?: boolean | ProfileCountOutputTypeCountExperiencesArgs
  projects?: boolean | ProfileCountOutputTypeCountProjectsArgs
  blogs?: boolean | ProfileCountOutputTypeCountBlogsArgs
}

/**
 * ProfileCountOutputType without action
 */
export type ProfileCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfileCountOutputType
   */
  select?: Prisma.ProfileCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ProfileCountOutputType without action
 */
export type ProfileCountOutputTypeCountExperiencesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ExperienceWhereInput
}

/**
 * ProfileCountOutputType without action
 */
export type ProfileCountOutputTypeCountProjectsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProjectWhereInput
}

/**
 * ProfileCountOutputType without action
 */
export type ProfileCountOutputTypeCountBlogsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BlogWhereInput
}


export type ProfileSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  avatar?: boolean
  banner?: boolean
  name?: boolean
  email?: boolean
  age?: boolean
  location?: boolean
  userId?: boolean
  username?: boolean
  bio?: boolean
  skills?: boolean
  github?: boolean
  twitter?: boolean
  linkedin?: boolean
  themeId?: boolean
  resume?: boolean
  tagline?: boolean
  bookAcall?: boolean
  views?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  experiences?: boolean | Prisma.Profile$experiencesArgs<ExtArgs>
  projects?: boolean | Prisma.Profile$projectsArgs<ExtArgs>
  blogs?: boolean | Prisma.Profile$blogsArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.ProfileCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["profile"]>

export type ProfileSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  avatar?: boolean
  banner?: boolean
  name?: boolean
  email?: boolean
  age?: boolean
  location?: boolean
  userId?: boolean
  username?: boolean
  bio?: boolean
  skills?: boolean
  github?: boolean
  twitter?: boolean
  linkedin?: boolean
  themeId?: boolean
  resume?: boolean
  tagline?: boolean
  bookAcall?: boolean
  views?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["profile"]>

export type ProfileSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  avatar?: boolean
  banner?: boolean
  name?: boolean
  email?: boolean
  age?: boolean
  location?: boolean
  userId?: boolean
  username?: boolean
  bio?: boolean
  skills?: boolean
  github?: boolean
  twitter?: boolean
  linkedin?: boolean
  themeId?: boolean
  resume?: boolean
  tagline?: boolean
  bookAcall?: boolean
  views?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["profile"]>

export type ProfileSelectScalar = {
  id?: boolean
  avatar?: boolean
  banner?: boolean
  name?: boolean
  email?: boolean
  age?: boolean
  location?: boolean
  userId?: boolean
  username?: boolean
  bio?: boolean
  skills?: boolean
  github?: boolean
  twitter?: boolean
  linkedin?: boolean
  themeId?: boolean
  resume?: boolean
  tagline?: boolean
  bookAcall?: boolean
  views?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ProfileOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "avatar" | "banner" | "name" | "email" | "age" | "location" | "userId" | "username" | "bio" | "skills" | "github" | "twitter" | "linkedin" | "themeId" | "resume" | "tagline" | "bookAcall" | "views" | "createdAt" | "updatedAt", ExtArgs["result"]["profile"]>
export type ProfileInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  experiences?: boolean | Prisma.Profile$experiencesArgs<ExtArgs>
  projects?: boolean | Prisma.Profile$projectsArgs<ExtArgs>
  blogs?: boolean | Prisma.Profile$blogsArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.ProfileCountOutputTypeDefaultArgs<ExtArgs>
}
export type ProfileIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type ProfileIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $ProfilePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Profile"
  objects: {
    experiences: Prisma.$ExperiencePayload<ExtArgs>[]
    projects: Prisma.$ProjectPayload<ExtArgs>[]
    blogs: Prisma.$BlogPayload<ExtArgs>[]
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    avatar: string | null
    banner: string | null
    name: string | null
    email: string | null
    age: number | null
    location: string | null
    userId: string
    username: string | null
    bio: string | null
    skills: string[]
    github: string | null
    twitter: string | null
    linkedin: string | null
    themeId: string
    resume: string | null
    tagline: string | null
    bookAcall: string | null
    views: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["profile"]>
  composites: {}
}

export type ProfileGetPayload<S extends boolean | null | undefined | ProfileDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProfilePayload, S>

export type ProfileCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProfileFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProfileCountAggregateInputType | true
  }

export interface ProfileDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Profile'], meta: { name: 'Profile' } }
  /**
   * Find zero or one Profile that matches the filter.
   * @param {ProfileFindUniqueArgs} args - Arguments to find a Profile
   * @example
   * // Get one Profile
   * const profile = await prisma.profile.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProfileFindUniqueArgs>(args: Prisma.SelectSubset<T, ProfileFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProfileClient<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Profile that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProfileFindUniqueOrThrowArgs} args - Arguments to find a Profile
   * @example
   * // Get one Profile
   * const profile = await prisma.profile.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProfileFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProfileFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProfileClient<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Profile that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileFindFirstArgs} args - Arguments to find a Profile
   * @example
   * // Get one Profile
   * const profile = await prisma.profile.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProfileFindFirstArgs>(args?: Prisma.SelectSubset<T, ProfileFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProfileClient<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Profile that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileFindFirstOrThrowArgs} args - Arguments to find a Profile
   * @example
   * // Get one Profile
   * const profile = await prisma.profile.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProfileFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProfileFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProfileClient<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Profiles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Profiles
   * const profiles = await prisma.profile.findMany()
   * 
   * // Get first 10 Profiles
   * const profiles = await prisma.profile.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const profileWithIdOnly = await prisma.profile.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProfileFindManyArgs>(args?: Prisma.SelectSubset<T, ProfileFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Profile.
   * @param {ProfileCreateArgs} args - Arguments to create a Profile.
   * @example
   * // Create one Profile
   * const Profile = await prisma.profile.create({
   *   data: {
   *     // ... data to create a Profile
   *   }
   * })
   * 
   */
  create<T extends ProfileCreateArgs>(args: Prisma.SelectSubset<T, ProfileCreateArgs<ExtArgs>>): Prisma.Prisma__ProfileClient<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Profiles.
   * @param {ProfileCreateManyArgs} args - Arguments to create many Profiles.
   * @example
   * // Create many Profiles
   * const profile = await prisma.profile.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProfileCreateManyArgs>(args?: Prisma.SelectSubset<T, ProfileCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Profiles and returns the data saved in the database.
   * @param {ProfileCreateManyAndReturnArgs} args - Arguments to create many Profiles.
   * @example
   * // Create many Profiles
   * const profile = await prisma.profile.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Profiles and only return the `id`
   * const profileWithIdOnly = await prisma.profile.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProfileCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProfileCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Profile.
   * @param {ProfileDeleteArgs} args - Arguments to delete one Profile.
   * @example
   * // Delete one Profile
   * const Profile = await prisma.profile.delete({
   *   where: {
   *     // ... filter to delete one Profile
   *   }
   * })
   * 
   */
  delete<T extends ProfileDeleteArgs>(args: Prisma.SelectSubset<T, ProfileDeleteArgs<ExtArgs>>): Prisma.Prisma__ProfileClient<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Profile.
   * @param {ProfileUpdateArgs} args - Arguments to update one Profile.
   * @example
   * // Update one Profile
   * const profile = await prisma.profile.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProfileUpdateArgs>(args: Prisma.SelectSubset<T, ProfileUpdateArgs<ExtArgs>>): Prisma.Prisma__ProfileClient<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Profiles.
   * @param {ProfileDeleteManyArgs} args - Arguments to filter Profiles to delete.
   * @example
   * // Delete a few Profiles
   * const { count } = await prisma.profile.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProfileDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProfileDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Profiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Profiles
   * const profile = await prisma.profile.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProfileUpdateManyArgs>(args: Prisma.SelectSubset<T, ProfileUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Profiles and returns the data updated in the database.
   * @param {ProfileUpdateManyAndReturnArgs} args - Arguments to update many Profiles.
   * @example
   * // Update many Profiles
   * const profile = await prisma.profile.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Profiles and only return the `id`
   * const profileWithIdOnly = await prisma.profile.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProfileUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProfileUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Profile.
   * @param {ProfileUpsertArgs} args - Arguments to update or create a Profile.
   * @example
   * // Update or create a Profile
   * const profile = await prisma.profile.upsert({
   *   create: {
   *     // ... data to create a Profile
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Profile we want to update
   *   }
   * })
   */
  upsert<T extends ProfileUpsertArgs>(args: Prisma.SelectSubset<T, ProfileUpsertArgs<ExtArgs>>): Prisma.Prisma__ProfileClient<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Profiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileCountArgs} args - Arguments to filter Profiles to count.
   * @example
   * // Count the number of Profiles
   * const count = await prisma.profile.count({
   *   where: {
   *     // ... the filter for the Profiles we want to count
   *   }
   * })
  **/
  count<T extends ProfileCountArgs>(
    args?: Prisma.Subset<T, ProfileCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProfileCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Profile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProfileAggregateArgs>(args: Prisma.Subset<T, ProfileAggregateArgs>): Prisma.PrismaPromise<GetProfileAggregateType<T>>

  /**
   * Group by Profile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProfileGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProfileGroupByArgs['orderBy'] }
      : { orderBy?: ProfileGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProfileGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProfileGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Profile model
 */
readonly fields: ProfileFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Profile.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProfileClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  experiences<T extends Prisma.Profile$experiencesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Profile$experiencesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExperiencePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  projects<T extends Prisma.Profile$projectsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Profile$projectsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  blogs<T extends Prisma.Profile$blogsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Profile$blogsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BlogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Profile model
 */
export interface ProfileFieldRefs {
  readonly id: Prisma.FieldRef<"Profile", 'String'>
  readonly avatar: Prisma.FieldRef<"Profile", 'String'>
  readonly banner: Prisma.FieldRef<"Profile", 'String'>
  readonly name: Prisma.FieldRef<"Profile", 'String'>
  readonly email: Prisma.FieldRef<"Profile", 'String'>
  readonly age: Prisma.FieldRef<"Profile", 'Int'>
  readonly location: Prisma.FieldRef<"Profile", 'String'>
  readonly userId: Prisma.FieldRef<"Profile", 'String'>
  readonly username: Prisma.FieldRef<"Profile", 'String'>
  readonly bio: Prisma.FieldRef<"Profile", 'String'>
  readonly skills: Prisma.FieldRef<"Profile", 'String[]'>
  readonly github: Prisma.FieldRef<"Profile", 'String'>
  readonly twitter: Prisma.FieldRef<"Profile", 'String'>
  readonly linkedin: Prisma.FieldRef<"Profile", 'String'>
  readonly themeId: Prisma.FieldRef<"Profile", 'String'>
  readonly resume: Prisma.FieldRef<"Profile", 'String'>
  readonly tagline: Prisma.FieldRef<"Profile", 'String'>
  readonly bookAcall: Prisma.FieldRef<"Profile", 'String'>
  readonly views: Prisma.FieldRef<"Profile", 'Int'>
  readonly createdAt: Prisma.FieldRef<"Profile", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Profile", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Profile findUnique
 */
export type ProfileFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileInclude<ExtArgs> | null
  /**
   * Filter, which Profile to fetch.
   */
  where: Prisma.ProfileWhereUniqueInput
}

/**
 * Profile findUniqueOrThrow
 */
export type ProfileFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileInclude<ExtArgs> | null
  /**
   * Filter, which Profile to fetch.
   */
  where: Prisma.ProfileWhereUniqueInput
}

/**
 * Profile findFirst
 */
export type ProfileFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileInclude<ExtArgs> | null
  /**
   * Filter, which Profile to fetch.
   */
  where?: Prisma.ProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Profiles to fetch.
   */
  orderBy?: Prisma.ProfileOrderByWithRelationInput | Prisma.ProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Profiles.
   */
  cursor?: Prisma.ProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Profiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Profiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Profiles.
   */
  distinct?: Prisma.ProfileScalarFieldEnum | Prisma.ProfileScalarFieldEnum[]
}

/**
 * Profile findFirstOrThrow
 */
export type ProfileFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileInclude<ExtArgs> | null
  /**
   * Filter, which Profile to fetch.
   */
  where?: Prisma.ProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Profiles to fetch.
   */
  orderBy?: Prisma.ProfileOrderByWithRelationInput | Prisma.ProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Profiles.
   */
  cursor?: Prisma.ProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Profiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Profiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Profiles.
   */
  distinct?: Prisma.ProfileScalarFieldEnum | Prisma.ProfileScalarFieldEnum[]
}

/**
 * Profile findMany
 */
export type ProfileFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileInclude<ExtArgs> | null
  /**
   * Filter, which Profiles to fetch.
   */
  where?: Prisma.ProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Profiles to fetch.
   */
  orderBy?: Prisma.ProfileOrderByWithRelationInput | Prisma.ProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Profiles.
   */
  cursor?: Prisma.ProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Profiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Profiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Profiles.
   */
  distinct?: Prisma.ProfileScalarFieldEnum | Prisma.ProfileScalarFieldEnum[]
}

/**
 * Profile create
 */
export type ProfileCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileInclude<ExtArgs> | null
  /**
   * The data needed to create a Profile.
   */
  data: Prisma.XOR<Prisma.ProfileCreateInput, Prisma.ProfileUncheckedCreateInput>
}

/**
 * Profile createMany
 */
export type ProfileCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Profiles.
   */
  data: Prisma.ProfileCreateManyInput | Prisma.ProfileCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Profile createManyAndReturn
 */
export type ProfileCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * The data used to create many Profiles.
   */
  data: Prisma.ProfileCreateManyInput | Prisma.ProfileCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Profile update
 */
export type ProfileUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileInclude<ExtArgs> | null
  /**
   * The data needed to update a Profile.
   */
  data: Prisma.XOR<Prisma.ProfileUpdateInput, Prisma.ProfileUncheckedUpdateInput>
  /**
   * Choose, which Profile to update.
   */
  where: Prisma.ProfileWhereUniqueInput
}

/**
 * Profile updateMany
 */
export type ProfileUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Profiles.
   */
  data: Prisma.XOR<Prisma.ProfileUpdateManyMutationInput, Prisma.ProfileUncheckedUpdateManyInput>
  /**
   * Filter which Profiles to update
   */
  where?: Prisma.ProfileWhereInput
  /**
   * Limit how many Profiles to update.
   */
  limit?: number
}

/**
 * Profile updateManyAndReturn
 */
export type ProfileUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * The data used to update Profiles.
   */
  data: Prisma.XOR<Prisma.ProfileUpdateManyMutationInput, Prisma.ProfileUncheckedUpdateManyInput>
  /**
   * Filter which Profiles to update
   */
  where?: Prisma.ProfileWhereInput
  /**
   * Limit how many Profiles to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Profile upsert
 */
export type ProfileUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileInclude<ExtArgs> | null
  /**
   * The filter to search for the Profile to update in case it exists.
   */
  where: Prisma.ProfileWhereUniqueInput
  /**
   * In case the Profile found by the `where` argument doesn't exist, create a new Profile with this data.
   */
  create: Prisma.XOR<Prisma.ProfileCreateInput, Prisma.ProfileUncheckedCreateInput>
  /**
   * In case the Profile was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProfileUpdateInput, Prisma.ProfileUncheckedUpdateInput>
}

/**
 * Profile delete
 */
export type ProfileDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileInclude<ExtArgs> | null
  /**
   * Filter which Profile to delete.
   */
  where: Prisma.ProfileWhereUniqueInput
}

/**
 * Profile deleteMany
 */
export type ProfileDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Profiles to delete
   */
  where?: Prisma.ProfileWhereInput
  /**
   * Limit how many Profiles to delete.
   */
  limit?: number
}

/**
 * Profile.experiences
 */
export type Profile$experiencesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Experience
   */
  select?: Prisma.ExperienceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Experience
   */
  omit?: Prisma.ExperienceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExperienceInclude<ExtArgs> | null
  where?: Prisma.ExperienceWhereInput
  orderBy?: Prisma.ExperienceOrderByWithRelationInput | Prisma.ExperienceOrderByWithRelationInput[]
  cursor?: Prisma.ExperienceWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ExperienceScalarFieldEnum | Prisma.ExperienceScalarFieldEnum[]
}

/**
 * Profile.projects
 */
export type Profile$projectsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  where?: Prisma.ProjectWhereInput
  orderBy?: Prisma.ProjectOrderByWithRelationInput | Prisma.ProjectOrderByWithRelationInput[]
  cursor?: Prisma.ProjectWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProjectScalarFieldEnum | Prisma.ProjectScalarFieldEnum[]
}

/**
 * Profile.blogs
 */
export type Profile$blogsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Blog
   */
  select?: Prisma.BlogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Blog
   */
  omit?: Prisma.BlogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BlogInclude<ExtArgs> | null
  where?: Prisma.BlogWhereInput
  orderBy?: Prisma.BlogOrderByWithRelationInput | Prisma.BlogOrderByWithRelationInput[]
  cursor?: Prisma.BlogWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.BlogScalarFieldEnum | Prisma.BlogScalarFieldEnum[]
}

/**
 * Profile without action
 */
export type ProfileDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profile
   */
  select?: Prisma.ProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profile
   */
  omit?: Prisma.ProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileInclude<ExtArgs> | null
}
