import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { DM_Sans, Instrument_Serif, Geist } from "next/font/google";
import Providers from "./providers";
import { Toaster } from "react-hot-toast";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const serif = Instrument_Serif({
  subsets: ["latin"],
  variable: "--font-serif-display",
  weight: "400",
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn( serif.variable, "font-sans", geist.variable)}
      suppressHydrationWarning
    >
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{if(localStorage.getItem("lf-theme")==="dark")document.documentElement.classList.add("dark")}catch(e){}})();`,
          }}
        />
      </head>
      <body className={cn(geist.variable, serif.variable, "antialiased")}>
        <Toaster position="bottom-right" />
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}