-- AlterTable
ALTER TABLE "Blog" ALTER COLUMN "title" DROP DEFAULT,
ALTER COLUMN "description" DROP DEFAULT,
ALTER COLUMN "date" DROP DEFAULT,
ALTER COLUMN "blogLink" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Experience" ALTER COLUMN "companyName" DROP DEFAULT,
ALTER COLUMN "role" DROP DEFAULT,
ALTER COLUMN "date" DROP DEFAULT,
ALTER COLUMN "description" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Profile" ALTER COLUMN "bio" DROP DEFAULT,
ALTER COLUMN "github" DROP DEFAULT,
ALTER COLUMN "twitter" DROP DEFAULT,
ALTER COLUMN "linkedin" DROP DEFAULT,
ALTER COLUMN "age" DROP DEFAULT,
ALTER COLUMN "avatar" DROP DEFAULT,
ALTER COLUMN "banner" DROP DEFAULT,
ALTER COLUMN "location" DROP DEFAULT,
ALTER COLUMN "name" DROP DEFAULT,
ALTER COLUMN "username" DROP DEFAULT,
ALTER COLUMN "email" DROP DEFAULT,
ALTER COLUMN "skills" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Project" ALTER COLUMN "title" DROP DEFAULT,
ALTER COLUMN "description" DROP DEFAULT,
ALTER COLUMN "date" DROP DEFAULT,
ALTER COLUMN "githubLink" DROP DEFAULT,
ALTER COLUMN "projectLink" DROP DEFAULT,
ALTER COLUMN "techstack" DROP DEFAULT;
